In [2]:
import numpy as np

In [25]:
N, T, V, D = 2, 4, 5, 3

x = np.asarray([[0, 3, 1, 2], [2, 1, 0, 3]])
W = np.linspace(0, 1, num=V*D).reshape(V, D)
print x
print W
N, T = x.shape
V, D = W.shape
dW = np.zeros_like(W)
pass
  
np.add.at(dW, x, 1)
print dW

[[0 3 1 2]
 [2 1 0 3]]
[[ 0.          0.07142857  0.14285714]
 [ 0.21428571  0.28571429  0.35714286]
 [ 0.42857143  0.5         0.57142857]
 [ 0.64285714  0.71428571  0.78571429]
 [ 0.85714286  0.92857143  1.        ]]
[[ 2.  2.  2.]
 [ 2.  2.  2.]
 [ 2.  2.  2.]
 [ 2.  2.  2.]
 [ 0.  0.  0.]]


In [1]:
a = np.arange(10)
b = np.add.at(a, [1,2], 2)
print a

NameError: name 'np' is not defined

In [12]:
a = np.zeros((5,2))
b = np.zeros((5,2))
c = np.append(a,[b,a], axis = 0)
print c

ValueError: all the input arrays must have same number of dimensions